### ISSUE TITLE
tempAirTriple development tasks

### ISSUE THREAD

**Issue by rhlee12** [NEONScience/NEON-IS-data-processing#72]
#### Steps to stand up pipelines:

- [x] group 2D wind**, PRT, Fan data in `tempAirTriple_related_location_group`
- [x] filter data
    - [x]  PRT data, flags, loc, etc in a PRT repo filter `tempAirTriple_prt`
    - [x] filter wind, Fan info in repo filter. _Just fan at this point?_**
- [x] ~Calibrate PRT data~
- [x] Regularize all PRT data
- [ ] Pair-wise difference module
    - [ ] Make 8 averaging flags based on PRT pair-wise check outcome, passed in different data column?
- [ ] Thresholds
    - [x] `tempAirTriple_threshold_filter`
    - [ ] `tempAirTriple_threshold_select`
- [ ] Group data (incl. pair-wise) + thresholds
- [ ] `timeseries_padder`
- [ ] QA/QC
    - [ ] Basic QA/QC on regular, padded PRT data
    - [ ] Group PRT w/ 2D wind, fan data**
    - [ ] Special QA/QC w/ PRT + 2D, fan data**
    - [ ] Group both QA/QC sets**
    - [ ] Group Flags**
- [ ] L1 QM generation on flags**
- [ ] Pre-stat grouping (uncert, QC data, and regularized data)**
- [ ] Stats and Uncert (including handling of pair-wise flag)**
- [ ] L1 grouping (L1 stats, uncert, and QMs)**
- [ ] Aggregated to 1, 30 min**

***

#### Roadblocks/Issues

- [x] Unable to recover Quay.io account
- [ ] Need Dawn L. to populate the data rate information in TAAT
    - [ ] **Will hard code for now, must remove when updated**
    - [ ] This issue seems to be the issue with the `threshold_select` module too:
    <img width="1089" alt="image" src="https://user-images.githubusercontent.com/19917092/105423308-82dacf00-5c02-11eb-9ef3-7fa4d0a02467.png">
- [ ] ** n-1 2D wind or Soni need to be mapped by CI

**Comment by covesturtevant** [comment]
@rhlee12 Are you in touch with quay.io to reset your account? If that doesn't work, maybe make a new quay.io account? if you do the latter, let Liz know your new username to add you to the quay.io teams.

Story ([NSE-7453](https://battelleecology.atlassian.net/browse/NSE-7463)) to add the context groups for aspirated-triple is in the current sprint, but release work has taken priority. Will let you know when it is complete.

**Comment by rhlee12** [comment]
@covesturtevant Found a better fix: I finally guessed it this morning. And thanks for the info on the context grouping.

Do you have ~15 mins to chat on the above to-dos and a pachyderm strategy sometime this week?

**Comment by covesturtevant** [comment]
@rhlee12 Nice guess! Yep, feel free to put something on my calendar; it's up to date.

**Comment by rhlee12** [comment]
Possible workaround for threshold contexts: don't use `aspirated-triple`, but use `temp` or similar in the filter step?

**Comment by rhlee12** [comment]
- [ ] Pass avg. flag into flags, as shown in the ATBD (1 flag per avg code, 8 total)
- [ ] Create variable, for data file, showing the PRTs used, e.g. 12, 13, 123, 23, etc...

**Comment by rhlee12** [comment]
- [ ] clean up the individual `tempAirTriple_` data modules
